# Generated by Django 4.1 on 2023-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('avatar', models.CharField(max_length=300, verbose_name='头像')),
                ('identity', models.IntegerField(default=0, verbose_name='身份')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
